import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { dbConnect } from "@/server/server";
import { Toaster } from "react-hot-toast";
import QueryProviders from "@/contexts/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const connected = await dbConnect();

  // console.log(connected);
  return (
    <html lang="en">
      <body className="bg-[#0B0F1A] text-white font-sans">
        <QueryProviders>{children}</QueryProviders>
      </body>

      <Toaster
        toastOptions={{
          style: {
            fontSize: "12px",
            fontWeight: "700",
          },

          success: {
            iconTheme: {
              primary: "black",
              secondary: "white",
            },
          },
        }}
        containerStyle={{ zIndex: 2147483647 }}
      />
    </html>
  );
}
