import { FormState, JournalEntry, Trade } from "@/types";

export const tradeFeatures = [
  {
    title: "Trading Plan Builder",
    description: "Build and manage your trading plans with ease.",
  },
  {
    title: "Automated Journal",
    description:
      "Keep track of your trades and emotions with an automated journal.",
  },
  {
    title: "Backtesting Engine",
    description:
      "Test your strategies against historical data to see how they would have performed.",
  },
  {
    title: "AI Insights",
    description:
      "Get AI-powered insights to help you make better trading decisions.",
  },
  {
    title: "Discipline Tracking",
    description:
      "Track your discipline and avoid emotional mistakes with our built-in tools.",
  },
  {
    title: "Advanced Analytics",
    description:
      "Analyze your trading performance with advanced analytics tools.",
  },
];

export const navItems = [
  { icon: "grid", label: "Dashboard", active: true },
  { icon: "plus", label: "New Trade" },
  { icon: "list", label: "Trades" },
  { icon: "search", label: "Search" },
];

export const premiumItems = [
  { emoji: "📊", label: "Reports" },
  { emoji: "📅", label: "Calendar" },
  { emoji: "📓", label: "Notebook" },
  { emoji: "📖", label: "Journal" },
  { emoji: "🧠", label: "Psychology" },
  { emoji: "🔢", label: "Risk Calculator" },
  { emoji: "🤖", label: "AI Coach Insights" },
  { emoji: "💬", label: "AI Analyst Chat" },
  { emoji: "📥", label: "File Import" },
  { emoji: "🎯", label: "Performance Goals" },
  { emoji: "📏", label: "Trading Rules" },
];

export const gettingStartedItems = [
  {
    title: "Log your first trade",
    desc: "Record a recent trade with entry, exit, and notes",
    icon: "chart",
  },
  {
    title: "Try the AI Coach",
    desc: "Ask for feedback on your trading or plan a session",
    icon: "chat",
  },
  {
    title: "Connect a broker",
    desc: "Import trades from MT4/MT5, Bybit, Binance, or KuCoin",
    icon: "link",
  },
  {
    title: "Set a performance goal",
    desc: "Track a target like win rate or monthly P&L",
    icon: "target",
  },
];

export const actionCards = [
  {
    title: "Log Your First Trade",
    desc: "Enter a recent trade with your setup, entry, exit, and notes. Takes about 2 minutes.",
    color: "blue",
    icon: "chart",
  },
  {
    title: "Connect Your Broker",
    desc: "Link MT4/MT5, Bybit, Binance, or KuCoin to import trades automatically.",
    color: "green",
    icon: "link",
  },
  {
    title: "Ask the AI Coach",
    desc: "Get personalized trading advice, analyze recent losses, or plan your next session.",
    color: "purple",
    icon: "chat",
  },
  {
    title: "Set a Goal",
    desc: "Define a trading goal — like win rate or monthly P&L — and track your progress.",
    color: "amber",
    icon: "target",
  },
];

export const cardIconColors: Record<string, { bg: string; stroke: string }> = {
  blue: { bg: "#1d3a6e", stroke: "#60a5fa" },
  green: { bg: "#14432a", stroke: "#34d399" },
  purple: { bg: "#2d1b5e", stroke: "#a78bfa" },
  amber: { bg: "#4a2e0a", stroke: "#fbbf24" },
};

export const links = [
  { icon: "grid", title: "Dashboard", href: "/dashboard" },
  {
    icon: "plus",
    title: "Trades",
    href: "/trades",
  },
  {
    icon: "link",
    title: "Trading Plan",
    href: "/trading-plan",
  },
  {
    icon: "chart",
    title: "Backtesting",
    href: "/backtesting",
  },
  { icon: "chat", title: "Journal", href: "/journal" },
  // {
  //   title: "Analytics",
  //   href: "/analytics",
  // },
];

export const tradeFeelings = [
  "Confident",
  "Patient",
  "Relaxed",
  "Inspired",
  "Focused",
  "Distracted",
  "Calm",
  "Anxious",
  "Disciplined",
  "Greed",
  "Fear",
  "Hope",
];

export const publicRoutes = [
  "/",
  "signup",
  "/login",
  "/forgotPassword",
  "/verifyOtp",
  "/resetPassword",
];

export const protectedRoutes = [
  "/charts",
  "/dashboard",
  "/trades",
  "/trading-plan",
  "/backtesting",
  "/journal",
  "/changePassword",
];

export const TIMEFRAMES = [
  "1m",
  "3m",
  "5m",
  "15m",
  "30m",
  "1H",
  "4H",
  "1D",
  "1W",
  "1M",
];

export type Timeframe = (typeof TIMEFRAMES)[number];

export const TRADER_TYPES = [
  "scalper",
  "day trader",
  "swing trader",
  "position trader",
] as const;

export type TraderType = (typeof TRADER_TYPES)[number];

export const InstrumentCats = [
  "Commodities",
  "Forex",
  "Stocks",
  "Crypto",
  "Indices",
  "Futures",
];

export const MOCK_STATS = {
  totalTrades: 48,
  wins: 27,
  losses: 16,
  breakevens: 5,
  winRate: 56.25,
  lossRate: 33.33,
  avgRR: 2.4,
  totalProfit: 3820,
  expectancy: 1.14,
  hasEdge: true,
  netProfit: 3820,
  grossProfit: 5640,
  grossLoss: -1820,
  profitFactor: 3.09,
  maxDrawdown: 6.2,
  finalBalance: 13820,
  initialBalance: 10000,
  edgeScore: 74,
};

export const MOCK_TRADES: Trade[] = [
  {
    id: 1,
    entryTime: "2024-01-08 09:15",
    exitTime: "2024-01-08 11:42",
    direction: "buy",
    entryPrice: 1.2654,
    exitPrice: 1.2748,
    stopLoss: 1.261,
    takeProfit: 1.276,
    riskReward: 2.1,
    profitLoss: 940,
    profitLossPercent: 9.4,
    outcome: "win",
    setupType: "BOS Retest",
    session: "London",
    notes: "Clean BOS with strong momentum",
  },
  {
    id: 2,
    entryTime: "2024-01-09 14:30",
    exitTime: "2024-01-09 16:00",
    direction: "sell",
    entryPrice: 1.278,
    exitPrice: 1.271,
    stopLoss: 1.282,
    takeProfit: 1.266,
    riskReward: 3.0,
    profitLoss: 700,
    profitLossPercent: 7.0,
    outcome: "win",
    setupType: "FVG Fill",
    session: "NY",
    notes: "Textbook FVG entry",
  },
  {
    id: 3,
    entryTime: "2024-01-10 08:00",
    exitTime: "2024-01-10 09:30",
    direction: "buy",
    entryPrice: 1.269,
    exitPrice: 1.2645,
    stopLoss: 1.2655,
    takeProfit: 1.276,
    riskReward: 2.0,
    profitLoss: -450,
    profitLossPercent: -4.5,
    outcome: "loss",
    setupType: "Liquidity Sweep",
    session: "London",
    notes: "Stopped out — false sweep",
  },
  {
    id: 4,
    entryTime: "2024-01-11 10:00",
    exitTime: "2024-01-11 13:15",
    direction: "sell",
    entryPrice: 1.272,
    exitPrice: 1.272,
    stopLoss: 1.276,
    takeProfit: 1.264,
    riskReward: 0,
    profitLoss: 0,
    profitLossPercent: 0,
    outcome: "breakeven",
    setupType: "OB Entry",
    session: "London",
    notes: "Moved SL to BE, reversed",
  },
  {
    id: 5,
    entryTime: "2024-01-12 15:00",
    exitTime: "2024-01-12 17:30",
    direction: "buy",
    entryPrice: 1.2598,
    exitPrice: 1.271,
    stopLoss: 1.2555,
    takeProfit: 1.273,
    riskReward: 2.6,
    profitLoss: 1120,
    profitLossPercent: 11.2,
    outcome: "win",
    setupType: "MSS + OB",
    session: "NY",
    notes: "Perfect MSS confirmation",
  },
  {
    id: 6,
    entryTime: "2024-01-15 09:00",
    exitTime: "2024-01-15 10:15",
    direction: "sell",
    entryPrice: 1.2745,
    exitPrice: 1.2698,
    stopLoss: 1.278,
    takeProfit: 1.2675,
    riskReward: 2.0,
    profitLoss: -350,
    profitLossPercent: -3.5,
    outcome: "loss",
    setupType: "BOS Retest",
    session: "London",
    notes: "News spike invalidated setup",
  },
  {
    id: 7,
    entryTime: "2024-01-16 14:00",
    exitTime: "2024-01-16 17:45",
    direction: "buy",
    entryPrice: 1.2612,
    exitPrice: 1.2748,
    stopLoss: 1.257,
    takeProfit: 1.278,
    riskReward: 3.2,
    profitLoss: 1360,
    profitLossPercent: 13.6,
    outcome: "win",
    setupType: "FVG Fill",
    session: "NY",
    notes: "Strong NY momentum trade",
  },
  {
    id: 8,
    entryTime: "2024-01-17 08:30",
    exitTime: "2024-01-17 11:00",
    direction: "sell",
    entryPrice: 1.279,
    exitPrice: 1.273,
    stopLoss: 1.2825,
    takeProfit: 1.2685,
    riskReward: 3.0,
    profitLoss: 600,
    profitLossPercent: 6.0,
    outcome: "win",
    setupType: "Liquidity Sweep",
    session: "London",
    notes: "Clean sweep above highs",
  },
];

export const MOCK_BACKTESTS = [
  {
    id: "bt_1",
    name: "London Breakout Test",
    tradingPlanName: "ICT Momentum Model",
    pair: "EURUSD",
    timeframe: "1H",
    startDate: "2024-01-01",
    endDate: "2024-02-01",
    status: "completed",
    createdAt: "2024-02-02",
  },
  {
    id: "bt_2",
    name: "Asia Range Fade",
    tradingPlanName: "Liquidity Sweep Model",
    pair: "GBPUSD",
    timeframe: "15m",
    startDate: "2024-03-01",
    endDate: "2024-03-20",
    status: "completed",
    createdAt: "2024-03-21",
  },
];

export const BULK_TRADES_WIN = [
  {
    direction: "buy",
    outcome: "win",
    entryTime: "2024-01-01T09:00:00Z",
    exitTime: "2024-01-01T11:30:00Z",
    entryPrice: 1.095,
    exitPrice: 1.101,
    stopLoss: 1.092,
    takeProfit: 1.101,
    riskReward: 2,
    profitLoss: 600,
    profitLossPercent: 6,
    setupType: "Breakout",
    session: "London",
    notes: "Clean breakout above resistance",
  },
  {
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-02T10:00:00Z",
    exitTime: "2024-01-02T12:00:00Z",
    entryPrice: 1.102,
    exitPrice: 1.106,
    stopLoss: 1.106,
    takeProfit: 1.095,
    riskReward: 2,
    profitLoss: -400,
    profitLossPercent: -4,
    setupType: "Reversal",
    session: "London",
    notes: "Fake reversal, continued trend",
  },
  {
    direction: "buy",
    outcome: "win",
    entryTime: "2024-01-03T13:00:00Z",
    exitTime: "2024-01-03T15:00:00Z",
    entryPrice: 1.09,
    exitPrice: 1.098,
    stopLoss: 1.086,
    takeProfit: 1.098,
    riskReward: 2,
    profitLoss: 800,
    profitLossPercent: 8,
    setupType: "Pullback",
    session: "New York",
    notes: "Strong bullish continuation",
  },
  {
    direction: "sell",
    outcome: "win",
    entryTime: "2024-01-04T08:30:00Z",
    exitTime: "2024-01-04T10:00:00Z",
    entryPrice: 1.1,
    exitPrice: 1.094,
    stopLoss: 1.103,
    takeProfit: 1.094,
    riskReward: 2,
    profitLoss: 600,
    profitLossPercent: 6,
    setupType: "Breakout",
    session: "London",
    notes: "Break below support",
  },
  {
    direction: "buy",
    outcome: "loss",
    entryTime: "2024-01-05T09:15:00Z",
    exitTime: "2024-01-05T10:45:00Z",
    entryPrice: 1.093,
    exitPrice: 1.089,
    stopLoss: 1.089,
    takeProfit: 1.1,
    riskReward: 2,
    profitLoss: -400,
    profitLossPercent: -4,
    setupType: "Pullback",
    session: "London",
    notes: "Stopped out quickly",
  },
  {
    direction: "sell",
    outcome: "breakeven",
    entryTime: "2024-01-06T11:00:00Z",
    exitTime: "2024-01-06T13:00:00Z",
    entryPrice: 1.097,
    exitPrice: 1.097,
    stopLoss: 1.101,
    takeProfit: 1.09,
    riskReward: 2,
    profitLoss: 0,
    profitLossPercent: 0,
    setupType: "Range",
    session: "New York",
    notes: "Moved SL to BE",
  },
  {
    direction: "buy",
    outcome: "win",
    entryTime: "2024-01-07T09:00:00Z",
    exitTime: "2024-01-07T12:00:00Z",
    entryPrice: 1.088,
    exitPrice: 1.096,
    stopLoss: 1.084,
    takeProfit: 1.096,
    riskReward: 2,
    profitLoss: 800,
    profitLossPercent: 8,
    setupType: "Reversal",
    session: "London",
    notes: "Strong bounce from support",
  },
  {
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-08T14:00:00Z",
    exitTime: "2024-01-08T15:30:00Z",
    entryPrice: 1.095,
    exitPrice: 1.099,
    stopLoss: 1.099,
    takeProfit: 1.088,
    riskReward: 2,
    profitLoss: -400,
    profitLossPercent: -4,
    setupType: "Breakout",
    session: "New York",
    notes: "False breakout",
  },
  {
    direction: "buy",
    outcome: "win",
    entryTime: "2024-01-09T10:00:00Z",
    exitTime: "2024-01-09T12:30:00Z",
    entryPrice: 1.091,
    exitPrice: 1.1,
    stopLoss: 1.087,
    takeProfit: 1.1,
    riskReward: 2.25,
    profitLoss: 900,
    profitLossPercent: 9,
    setupType: "Trend Continuation",
    session: "London",
    notes: "Momentum trade",
  },
  {
    direction: "sell",
    outcome: "win",
    entryTime: "2024-01-10T08:00:00Z",
    exitTime: "2024-01-10T09:30:00Z",
    entryPrice: 1.101,
    exitPrice: 1.094,
    stopLoss: 1.105,
    takeProfit: 1.094,
    riskReward: 2,
    profitLoss: 700,
    profitLossPercent: 7,
    setupType: "Reversal",
    session: "London",
    notes: "Overbought rejection",
  },
  {
    direction: "buy",
    outcome: "loss",
    entryTime: "2024-01-11T11:00:00Z",
    exitTime: "2024-01-11T12:00:00Z",
    entryPrice: 1.093,
    exitPrice: 1.089,
    stopLoss: 1.089,
    takeProfit: 1.1,
    riskReward: 2,
    profitLoss: -400,
    profitLossPercent: -4,
    setupType: "Pullback",
    session: "New York",
    notes: "Weak continuation",
  },
  {
    direction: "sell",
    outcome: "win",
    entryTime: "2024-01-12T09:00:00Z",
    exitTime: "2024-01-12T11:00:00Z",
    entryPrice: 1.098,
    exitPrice: 1.09,
    stopLoss: 1.102,
    takeProfit: 1.09,
    riskReward: 2,
    profitLoss: 800,
    profitLossPercent: 8,
    setupType: "Breakout",
    session: "London",
    notes: "Clean bearish structure",
  },
  {
    direction: "buy",
    outcome: "breakeven",
    entryTime: "2024-01-13T10:00:00Z",
    exitTime: "2024-01-13T12:00:00Z",
    entryPrice: 1.09,
    exitPrice: 1.09,
    stopLoss: 1.086,
    takeProfit: 1.098,
    riskReward: 2,
    profitLoss: 0,
    profitLossPercent: 0,
    setupType: "Range",
    session: "London",
    notes: "Choppy market",
  },
  {
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-14T13:00:00Z",
    exitTime: "2024-01-14T15:00:00Z",
    entryPrice: 1.097,
    exitPrice: 1.101,
    stopLoss: 1.101,
    takeProfit: 1.09,
    riskReward: 2,
    profitLoss: -400,
    profitLossPercent: -4,
    setupType: "Reversal",
    session: "New York",
    notes: "Late entry",
  },
  {
    direction: "buy",
    outcome: "win",
    entryTime: "2024-01-15T09:00:00Z",
    exitTime: "2024-01-15T11:30:00Z",
    entryPrice: 1.088,
    exitPrice: 1.097,
    stopLoss: 1.084,
    takeProfit: 1.097,
    riskReward: 2.25,
    profitLoss: 900,
    profitLossPercent: 9,
    setupType: "Trend Continuation",
    session: "London",
    notes: "Strong bullish impulse",
  },
];
export const BULK_TRADES_LOSS = [
  {
    id: "T1",
    direction: "buy",
    outcome: "loss",
    entryTime: "2024-01-01T09:10:00Z",
    exitTime: "2024-01-01T09:45:00Z",
    entryPrice: 1.102,
    exitPrice: 1.0985,
    stopLoss: 1.098,
    takeProfit: 1.108,
    riskReward: 2.0,
    profitLoss: -350,
    profitLossPercent: -3.5,
    setupType: "Breakout",
    session: "London",
    notes: "False breakout",
  },
  {
    id: "T2",
    direction: "sell",
    outcome: "breakeven",
    entryTime: "2024-01-02T13:00:00Z",
    exitTime: "2024-01-02T13:20:00Z",
    entryPrice: 1.205,
    exitPrice: 1.205,
    stopLoss: 1.209,
    takeProfit: 1.198,
    riskReward: 1.8,
    profitLoss: 0,
    profitLossPercent: 0,
    setupType: "Reversal",
    session: "New York",
    notes: "Closed early",
  },
  {
    id: "T3",
    direction: "buy",
    outcome: "loss",
    entryTime: "2024-01-03T08:00:00Z",
    exitTime: "2024-01-03T08:30:00Z",
    entryPrice: 1.31,
    exitPrice: 1.306,
    stopLoss: 1.305,
    takeProfit: 1.318,
    riskReward: 2.5,
    profitLoss: -400,
    profitLossPercent: -4.0,
    setupType: "Trend",
    session: "London",
    notes: "Weak continuation",
  },
  {
    id: "T4",
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-04T15:00:00Z",
    exitTime: "2024-01-04T15:25:00Z",
    entryPrice: 1.255,
    exitPrice: 1.259,
    stopLoss: 1.26,
    takeProfit: 1.245,
    riskReward: 2.2,
    profitLoss: -300,
    profitLossPercent: -3.0,
    setupType: "Breakout",
    session: "New York",
    notes: "Reversal hit SL",
  },
  {
    id: "T5",
    direction: "buy",
    outcome: "win",
    entryTime: "2024-01-05T07:45:00Z",
    exitTime: "2024-01-05T09:10:00Z",
    entryPrice: 1.09,
    exitPrice: 1.097,
    stopLoss: 1.085,
    takeProfit: 1.1,
    riskReward: 2.5,
    profitLoss: 700,
    profitLossPercent: 7.0,
    setupType: "Trend",
    session: "London",
    notes: "Clean move",
  },
  {
    id: "T6",
    direction: "sell",
    outcome: "breakeven",
    entryTime: "2024-01-06T12:30:00Z",
    exitTime: "2024-01-06T13:10:00Z",
    entryPrice: 1.315,
    exitPrice: 1.315,
    stopLoss: 1.32,
    takeProfit: 1.305,
    riskReward: 2.0,
    profitLoss: 0,
    profitLossPercent: 0,
    setupType: "Range",
    session: "New York",
    notes: "No follow through",
  },
  {
    id: "T7",
    direction: "buy",
    outcome: "loss",
    entryTime: "2024-01-07T10:00:00Z",
    exitTime: "2024-01-07T10:40:00Z",
    entryPrice: 1.175,
    exitPrice: 1.171,
    stopLoss: 1.17,
    takeProfit: 1.185,
    riskReward: 2.3,
    profitLoss: -400,
    profitLossPercent: -4.0,
    setupType: "Breakout",
    session: "London",
    notes: "Failed momentum",
  },
  {
    id: "T8",
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-08T14:20:00Z",
    exitTime: "2024-01-08T14:50:00Z",
    entryPrice: 1.265,
    exitPrice: 1.27,
    stopLoss: 1.27,
    takeProfit: 1.255,
    riskReward: 2.0,
    profitLoss: -500,
    profitLossPercent: -5.0,
    setupType: "Reversal",
    session: "New York",
    notes: "News spike",
  },
  {
    id: "T9",
    direction: "buy",
    outcome: "breakeven",
    entryTime: "2024-01-09T08:15:00Z",
    exitTime: "2024-01-09T08:50:00Z",
    entryPrice: 1.145,
    exitPrice: 1.145,
    stopLoss: 1.14,
    takeProfit: 1.155,
    riskReward: 2.0,
    profitLoss: 0,
    profitLossPercent: 0,
    setupType: "Trend",
    session: "London",
    notes: "Protected BE",
  },
  {
    id: "T10",
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-10T16:00:00Z",
    exitTime: "2024-01-10T16:30:00Z",
    entryPrice: 1.285,
    exitPrice: 1.289,
    stopLoss: 1.29,
    takeProfit: 1.275,
    riskReward: 2.0,
    profitLoss: -400,
    profitLossPercent: -4.0,
    setupType: "Range",
    session: "New York",
    notes: "Range breakout failed",
  },
  {
    id: "T11",
    direction: "buy",
    outcome: "win",
    entryTime: "2024-01-11T07:30:00Z",
    exitTime: "2024-01-11T09:00:00Z",
    entryPrice: 1.18,
    exitPrice: 1.187,
    stopLoss: 1.175,
    takeProfit: 1.19,
    riskReward: 2.4,
    profitLoss: 700,
    profitLossPercent: 7.0,
    setupType: "Trend",
    session: "London",
    notes: "Strong continuation",
  },
  {
    id: "T12",
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-12T13:45:00Z",
    exitTime: "2024-01-12T14:15:00Z",
    entryPrice: 1.305,
    exitPrice: 1.309,
    stopLoss: 1.31,
    takeProfit: 1.295,
    riskReward: 2.1,
    profitLoss: -400,
    profitLossPercent: -4.0,
    setupType: "Breakout",
    session: "New York",
    notes: "Stop hunt",
  },
  {
    id: "T13",
    direction: "buy",
    outcome: "breakeven",
    entryTime: "2024-01-13T09:10:00Z",
    exitTime: "2024-01-13T09:40:00Z",
    entryPrice: 1.225,
    exitPrice: 1.225,
    stopLoss: 1.22,
    takeProfit: 1.235,
    riskReward: 2.0,
    profitLoss: 0,
    profitLossPercent: 0,
    setupType: "Range",
    session: "London",
    notes: "Choppy market",
  },
  {
    id: "T14",
    direction: "sell",
    outcome: "loss",
    entryTime: "2024-01-14T15:30:00Z",
    exitTime: "2024-01-14T16:00:00Z",
    entryPrice: 1.295,
    exitPrice: 1.3,
    stopLoss: 1.3,
    takeProfit: 1.285,
    riskReward: 2.0,
    profitLoss: -500,
    profitLossPercent: -5.0,
    setupType: "Reversal",
    session: "New York",
    notes: "Wrong bias",
  },
  {
    id: "T15",
    direction: "buy",
    outcome: "loss",
    entryTime: "2024-01-15T08:20:00Z",
    exitTime: "2024-01-15T08:50:00Z",
    entryPrice: 1.135,
    exitPrice: 1.13,
    stopLoss: 1.13,
    takeProfit: 1.145,
    riskReward: 2.0,
    profitLoss: -500,
    profitLossPercent: -5.0,
    setupType: "Breakout",
    session: "London",
    notes: "Immediate rejection",
  },
];

export const INITIAL_FORM: FormState = {
  date: "",
  pair: "",
  type: "LONG",
  session: "London",
  exitTime: "",
  tradeOutcome: "TP",
  riskReward: "",
  entryCriteria: "",
  entryConfirmation: "",
  tradeManagement: "",
  mistakes: [],
  rightDeeds: [],
  feelings: [],
  note: "",
};

export const FORM_STEPS = ["Trade Info", "Execution", "Psychology", "Notes"];

export const MOCK: JournalEntry[] = [
  {
    _id: "1",
    date: "2024-04-10",
    pair: "EURUSD",
    type: "LONG",
    entryCriteria:
      "BOS on 1H with fair value gap below, price tapped into discount",
    entryConfirmation: "5m engulfing candle at OB, volume spike confirmation",
    session: "London",
    exitTime: "11:30",
    tradeOutcome: "TP",
    tradeManagement: "Moved SL to BE at 1R, held runner to 2R",
    riskReward: "1:2",
    mistakes: [],
    rightDeeds: [
      "Waited for confirmation",
      "Followed the plan",
      "Moved SL to BE",
    ],
    feelings: ["Confident", "Patient"],
    note: "Clean trade. HTF bias was clear, LTF gave perfect entry.",
    createdAt: "2024-04-10T11:30:00Z",
  },
  {
    _id: "2",
    date: "2024-04-09",
    pair: "XAUUSD",
    type: "SHORT",
    entryCriteria: "EQH liquidity sweep above Asian high, bearish OB on 15m",
    entryConfirmation: "MSS on 5m after sweep",
    session: "NY",
    exitTime: "15:45",
    tradeOutcome: "SL",
    tradeManagement: "Full position, no partials",
    riskReward: "1:2.5",
    mistakes: ["Entered too early", "Ignored HTF resistance"],
    rightDeeds: ["Kept SL intact"],
    feelings: ["Anxious", "Rushed"],
    note: "News spike hit SL. Should have checked the economic calendar.",
    createdAt: "2024-04-09T15:45:00Z",
  },
  {
    _id: "3",
    date: "2024-04-08",
    pair: "GBPUSD",
    type: "LONG",
    entryCriteria: "Premium to discount shift, FVG on 1H",
    entryConfirmation: "1H close above 0.5 fib with volume",
    session: "London",
    exitTime: "10:15",
    tradeOutcome: "BE",
    tradeManagement: "Moved SL to BE early, price came back and took BE",
    riskReward: "1:0",
    mistakes: ["Moved SL to BE too soon"],
    rightDeeds: ["Identified the setup correctly"],
    feelings: ["Calm", "Disciplined"],
    note: "Good setup, poor management. Would have hit TP if SL wasn't moved.",
    createdAt: "2024-04-08T10:15:00Z",
  },
];

export const FEELINGS_OPTIONS = [
  "Confident",
  "Patient",
  "Calm",
  "Disciplined",
  "Focused",
  "Anxious",
  "Rushed",
  "Greedy",
  "Fearful",
  "Frustrated",
  "FOMO",
  "Overconfident",
];
